server:
  port: 8081

rpc:
  serverPort: 8080
  serverHost: 127.0.0.1
  serializer: json
  registryConfig:
    address: http://localhost:6379
    registry: redis
    username: root
    password: 123456
  loadBalancer: consistentHash
  retryStrategy: exponentialBackoff
  tolerantStrategy: failSaft
